export interface DashboardUser {
    userName: string,
    userId: string,
    defaultGroupId: number,
    accountId: string,
    accountName: string,
    resellerId: string,
    impersonator: string,
    isUser: string,
    userEmail: string,
    userFirstName: string;
    userLastName: string;
    impersonatorEmail: string,
    impersonatorName: string,
    userCountry: string,
    enableLocationEdit: boolean,
    enableLocationUpload: boolean,
    languageSelected: string,
    userDisplayName: string,
    dashboardColor: string;
    accountLogo: string;
    swoopUserId: string,
    facebookEnabled: boolean,
    maximizerEnabled: boolean,
    reviewsEnabled: boolean,
    bingEnabled: boolean,
    googleRankingEnabled: boolean,
    gmbEnabled: boolean,
    visibilityEnabled: boolean,
    accuracyEnabled: boolean,
    analysisEnabled: boolean,
    showClientRef: boolean
    showLocationNumber: boolean
    hideGoogleRankDetails: boolean,
    enabledSites: string,
    reviewEnabledSites: string,
    contentAnalysisSites: string,
}